version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: mastra-postgres
    environment:
      POSTGRES_DB: mastra_rag
      POSTGRES_USER: mastra_user
      POSTGRES_PASSWORD: mastra_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
